### PR TITLE
Add aircraft to whitelist: Mi-24P, A-10C_2, AV8BNA, F-14B, F-16C_50, FA-18C_hornet, Su-33

### PR DESCRIPTION
**Pull request by Bango1999**
The following A/C have been **added** to the whitelist, according to their strings found in SLmodStats table I was supplied:

- Mi-24P
- A-10C_2
- AV8BNA
- F-14B
- F-16C_50
- FA-18C_hornet
- Su-33

I was unable to find the string matches for the following A/C in the SLmodStats, so they are **omitted**:

- P-47D
- JF-17
- Fw 190 A-8
- I-16
- MiG-19P
- Christen Eagle

### Test Plan<br>
Make sure you're using a `SLmodStats.lua` file containing usage statistics for 'newer' aircraft released since the AJS-37, and test that the new aircraft show up in the web view.

Additionally, test that you have K/D info now except for everything related to PvP, which is no longer present in the stats file that I can find.

### CODE REVIEW

**Comment by dirtymike0330** [comment]
playerkillsnull
updated1
updated2
Thanks for the quick turnaround! The aircraft additions worked perfectly and are now visible on the website. I also understand how I could update them should we need a module added. The only thing not populating is the "Player Kills" category: 

Looking at the S3functions.js, would it be just a matter of adding in specific ground units under the "var killObjects = ["  heading, as opposed to the current general categories? 

For example, some of the ground kills in the slmodstats.lua are listed as: 

                        ["ZTZ96B"] = 3,
                        ["Tank"] = 66,
                        ["GAZ-66"] = 1,
                        ["Soldier AK"] = 2,
                        ["Dry-cargo ship-2"] = 1,
                        ["Military staff"] = 1,
                        ["Warehouse"] = 15,
                        ["ATMZ-5"] = 4,
                        ["Cobra"] = 1,
                        ["A-10A"] = 41,
                        ["Soldier M4 GRG"] = 4,
                        ["Soldier M249"] = 3,
                        ["ZBD04A"] = 7,
                        ["KC-135"] = 22,
                        ["flak18"] = 1,
                        ["Dry-cargo ship-1"] = 1,
                        ["M978 HEMTT Tanker"] = 2,
                        ["Paratrooper AKS-74"] = 1,
                        ["Ural-4320T"] = 1,
                        ["M-113"] = 1,
                        ["T-72B"] = 9,
                        ["KC130"] = 12,
                        ["Mi-24P"] = 3,
                        ["MiG-29S"] = 7,
                        ["PT_76"] = 2,
                        ["M1043 HMMWV Armament"] = 4,
                        ["Tank 2"] = 15,
                        ["A-10C_2"] = 5,
                        ["C-130"] = 31,

I only have a cursory understanding of this kind of stuff and have never assisted on a git, but if you think what I mentioned is the solution, I have no problem trying it out to save you from any further work on a project you're not developing any further!

**Comment by Bango1999** [comment]
@rainman369 I appreciate the detailed feedback. I'll look deeper into this when I get home. I'm fairly confident you're on the right track but I'm confused why my old version doesn't still work, I was under the impression SLmod isn't being maintained or modified anymore.

**Comment by dirtymike0330** [comment]
Sounds good, thanks! I think the last update to it was 10-11 months ago IIRC. [https://github.com/mrSkortch](url)

**Comment by Bango1999** [comment]
The structure of that LUA table has changed quite a bit.

K/D info used to be tucked nicely into their own sections, but now everything is nested within the `times` section.

No sign of PvP data, so I removed them and put `N/A` in the table as a placeholder instead of messing with number of table columns.

Give it 1 more test w/ `develop` @rainman369 and make sure it works as described.

**Comment by dirtymike0330** [comment]
@Bango1999 works perfectly! Thanks so much for helping out with this!!

**Comment by Bango1999** [comment]
You're welcome. I'm glad S3 is still relevant and getting used. Enjoy!

**Comment by Bango1999** [comment]
@rainman369 I corrected 1 more thing just now. You can use `master` or `develop` branch and deaths should be accurate now too.

o7

**Pull request merged**
